### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by broseminal** [GuillermoElectrico/modbus-logger#1]
Can't seem to get this working, doesn't create a log either, when I close it:

 ^CTraceback (most recent call last):
  File "./read_modbus_device.py", line 305, in <module>
    func=lambda: collector.collect_and_store())
  File "./read_modbus_device.py", line 254, in repeat
    time.sleep(interval_sec - ((time.time() - starttime) % interval_sec))
KeyboardInterrupt

IDK???

**Comment by GuillermoElectrico** [comment]
Try to see it running with the --log DEBUG option to see where the error is giving you.

Have you executed setup.py? You may be missing something.

This code is operated in several installations without problems.
