### ISSUE TITLE
Module Not Found Error no module named Influxdb

### ISSUE THREAD

**Issue by karan369** [GuillermoElectrico/modbus-logger#2]
I have execution by command follwing.  shows errors
~/modbus-logger$ ./read_modbus_device.py
Traceback (most recent call last):
  File "./read_modbus_device.py", line 3, in <module>
    from influxdb import InfluxDBClient
ModuleNotFoundError: No module named 'influxdb'

But I tried in Ubunthu OS not raspberry Pi.

could you please suggest solutions?

**Comment by GuillermoElectrico** [comment]
Have you run "sudo python3 setup.py install" previously?

If error appears use previously: "sudo pip3 install setuptools"

**Comment by karan369** [comment]
Thanks for your reply.

yes, I run "sudo python3 setup.py install",  No errors , But now showing error like this

`~/modbus-logger$ ./read_modbus_device.py
Traceback (most recent call last):
  File "./read_modbus_device.py", line 301, in <module>
    device_yaml=args.devices)
  File "./read_modbus_device.py", line 29, in __init__
    for influx_config in sorted(self.get_influxdb(), key=lambda x:sorted(x.keys())):
TypeError: 'NoneType' object is not iterable
`

**Comment by GuillermoElectrico** [comment]
What version of PyYAML are you using?

Try with "sudo pip3 install -U PyYAML" to update for 5.1

**Comment by karan369** [comment]
After PyYAML update 5.1.
Thanks . Its working perfectly now. Data polling from meters and stored db.

But Data Storing is not stored real time or actual time. This is some difference actual and stored time. Why its stored like this.
Stored Time: 'T17:04:18.092446Z'  
Actual time: 'T 22:34:55'.

**Comment by GuillermoElectrico** [comment]
The first (ending in Z) is Zulu time, the second will depend on the geographical area.

**Comment by karan369** [comment]
how to resolve this ?.. I want to stored my time zone.

**Comment by GuillermoElectrico** [comment]
You will have to modify lines 67 and 70 to adjust it. (If you use grafana to see the data, it would not be necessary, since it adjusts itself to the local time)

**Comment by karan369** [comment]
Okay.well.

Thank you very much for your support. I will testing further one by one.
