### ISSUE TITLE
Variable Parmeter update in Grafana Dashboard

### ISSUE THREAD

**Issue by karan369** [GuillermoElectrico/modbus-logger#4]
Hi,

Have a nice day !!

I want to update variable parameter and selecting, using drop down, variables in metric queries and in panel titles in Grafana dashboard. But this is not work well (Graph). How can I modify that. Please see the attached images. Could you please support me for further developing this code.

![Screenshot2020-05-11T14-58-12 254Z](https://user-images.githubusercontent.com/48491061/81577167-c1a75c80-93c6-11ea-8237-0d79552c6ecc.png)

**Comment by GuillermoElectrico** [comment]
Sorry, but I don't have so much experience or knowledge to help you with grafana.

**Comment by karan369** [comment]
Okay.Thanks.

Any possible to change Measurement influx data in the python script.

In this script shown " ModbusLog" Measurement only.

If example more measurement model.
My schematic model
Measurement: V1 , tag sets (id: 1, feeder name: Incomer)
Measurement: V2 , tag sets (id: 1, feeder name: Incomer)
Measurement: V2 , tag sets (id: 1, feeder name: Incomer)
.....
...
Measurement: V1 , tag sets (id: 2, feeder name: Feeder1)
Measurement: V2 , tag sets (id: 2, feeder name: Feeder1)
Measurement: V2 , tag sets (id: 2, feeder name: Feeder1)

Is it possible to change in python script.

**Comment by GuillermoElectrico** [comment]
I don't understand what you mean, for what you want you just have to edit the devices.yml file and add as many devices (and their names) as you want.

What you have to work with at grafana is with the tag meter not with measurement if you have multiple devices.

Measurement refers to the data source (the logger) not the read or queried device.
