### ISSUE TITLE
Device error

### ISSUE THREAD

**Issue by karan369** [GuillermoElectrico/modbus-logger#5]
Hi,

Hope, you doing great.

I tried testing through RS485 to USB Converter, If first device is offline (No power supply), then all devices failed 
its showing error like.

`Devices:
Reloading device map as file changed
Failed to re-load device map, going on with the old one.
while parsing a block mapping
  in "devices.yml", line 1, column 1
expected <block end>, but found '<block sequence start>'
  in "devices.yml", line 13, column 3
Traceback (most recent call last):
  File "./read_modbus_device.py", line 301, in <module>
    device_yaml=args.devices)
  File "./read_modbus_device.py", line 36, in __init__
    for device in sorted(self.get_devices(), key=lambda x:sorted(x.keys())):
TypeError: 'NoneType' object is not iterable
`

How to solve this issue? If you have a solution.

**Comment by GuillermoElectrico** [comment]
This has never happened to me, but the way I see it, it seems that the devices.yml file is badly formatted, it doesn't seem like a communication problem.

What devices are you using?

**Comment by karan369** [comment]
Thanks. I will check the yml.file.

My device is Energy Meter with Modbus RTU.
