### ISSUE TITLE
Need help -Modbus Input Register

### ISSUE THREAD

**Issue by karan369** [GuillermoElectrico/modbus-logger#6]
Hi,

Hope you doing great.

Recently I checked one type of Energy Meter.
These, communication address details as follows,

1. Voltage-1
Address: 30000, Length ( Register): 2, Data Structure: Float

I tried Meter.yml
```
Voltage 1:
 - 3 # Adress dec data
 - 2 # Length word
 - 1 # Data Type. 1=Float(ABCD), 2=Long(ABCD), 3=Integer, 4=Long(CDAB)
```

But not showing actual value, showing like
9.669600479022927e+36

How can I get actual value, any possible way to convert. please do the needful.

**Comment by GuillermoElectrico** [comment]
Address: 30000 its not 3 in address dec data, is 0.

**Comment by karan369** [comment]
Also tried not showing like exponential value.

> Address: 30000 its not 3 in address dec data, is 0.

**Comment by GuillermoElectrico** [comment]
What model of meter are you using?

**Comment by karan369** [comment]
> What model of meter are you using?

SELCE MFM384 model

please refer address map
![selec modbus](https://user-images.githubusercontent.com/48491061/107411748-e6d32200-6b34-11eb-975d-6280f294e751.png)

**Comment by karan369** [comment]
Can't get the error from ELITE 440 model
![Screenshot_20210210_001754](https://user-images.githubusercontent.com/48491061/107412363-97412600-6b35-11eb-8236-cb276a457a32.jpg)

**Comment by GuillermoElectrico** [comment]
Strange, that may be a meter problem or the documentation is not right.

You have tried to fill the values directly from a PC using other software (such as qModMaster or similar).

By any chance, have you tried to read the values using function 3 instead of 4 in meters.yam?

**Comment by karan369** [comment]
> Strange, that may be a meter problem or the documentation is not right.
> 
> You have tried to fill the values directly from a PC using other software (such as qModMaster or similar).
> 
> By any chance, have you tried to read the values using function 3 instead of 4 in meters.yam?

I think so...I will try.

And Thanks lot for your support.

**Comment by karan369** [comment]
Now showing error like this
```
TypeError: not all arguments converted during string formatting
Call stack:
  File "./read_energy_meter.py", line 342, in <module>
    func=lambda: collector.collect_and_store())
  File "./read_energy_meter.py", line 295, in repeat
    func(*args, **kwargs)
  File "./read_energy_meter.py", line 342, in <lambda>
    func=lambda: collector.collect_and_store())
  File "./read_energy_meter.py", line 160, in collect_and_store
    log.error("Unexpected error:", sys.exc_info()[0])
Message: 'Unexpected error:'
Arguments: (<class 'modbus_tk.exceptions.ModbusInvalidResponseError'>,)
Response length is invalid 0

```

**Comment by GuillermoElectrico** [comment]
That error is a communication problem, or the wiring is not good, or the resistors are not good or the meter does not respond well (or the USB adapter is falsifying)

It is not usual (it has not happened to me in a long time) but sometimes I have had to restart the computer because of the USB adapter. I have replaced in some places with other models from other brands, and so far, none have failed me.

**Comment by karan369** [comment]
> That error is a communication problem, or the wiring is not good, or the resistors are not good or the meter does not respond well (or the USB adapter is falsifying)
> 
> It is not usual (it has not happened to me in a long time) but sometimes I have had to restart the computer because of the USB adapter. I have replaced in some places with other models from other brands, and so far, none have failed me.

Thank you for your valuable points. I will considering in future work. Thanks again.

**Comment by karan369** [comment]
Hi,

I checked with ModbusTester in another PC, its communicated Okay.

But If run this script showing error like this

`TypeError: not all arguments converted during string formatting
Call stack:
  File "./read_energy_meter.py", line 342, in <module>
    func=lambda: collector.collect_and_store())
  File "./read_energy_meter.py", line 295, in repeat
    func(*args, **kwargs)
  File "./read_energy_meter.py", line 342, in <lambda>
    func=lambda: collector.collect_and_store())
  File "./read_energy_meter.py", line 160, in collect_and_store
    log.error("Unexpected error:", sys.exc_info()[0])
Message: 'Unexpected error:'
Arguments: (<class 'modbus_tk.exceptions.ModbusError'>,)
Modbus Error: Exception code = 2- Code=2
Data not written! in Local InfluxDB
400: {"error":"unable to parse 'EnergyMeters,id=1,meter=Secure-Test-1 1612968047496739000': invalid field format"}
400: {"error":"unable to parse 'EnergyMeters,id=1,meter=Secure-Test-1 1612968047496739000': invalid field format"}
`
Please fins the attached yml file settings.
SDM120.yml

- VTest :
- 100 # Adress decimal
- 2 # Length word
 - 1 # Data Type. 1=Float(ABCD), 2=Long(ABCD), 3=Integer, 4=Long(CDAB), 5=Word (Unsigned Int), 6=Dword (Unsigned Long)

 
meters.yml
meters:
    - name : Secure-Test-1
      type : SDM120.yml
      conexion: R  # R = RTU 232/485 | T = TCP IPv4
      id : 1     # this is the slave address number
      baudrate : 9600   # Baud
      bytesize : 8
      parity : 'N' # 'N' = none | 'E' = even | 'O' = odd | 'S' = space| 'M' = mark
      stopbits : 1
      timeout  : 1   # seconds
      function : 3    # 3 = Read Holding register (40000) or 4 = Read Input register (30000)

**Comment by GuillermoElectrico** [comment]
The problem that you show is InfluxDB, it is not able to write the data. Error 400.

It seems that you want to write different data in the same field, but in different formats (as if two meters of different brands want to record the same data). Try saving to another database.

**Comment by karan369** [comment]
> The problem that you show is InfluxDB, it is not able to write the data. Error 400.
> 
> It seems that you want to write different data in the same field, but in different formats (as if two meters of different brands want to record the same data). Try saving to another data

> After reviewing the documentation, the SDM120 has nothing at address 100.

Now I changed 99 data is written,But value show like exponential -6.436877082672377e+22

**Comment by GuillermoElectrico** [comment]
After reviewing the documentation, the SDM120 has nothing at address 100.

**Comment by karan369** [comment]
Please go through this document 
![Screenshot_20210210_001754](https://user-images.githubusercontent.com/48491061/107557551-c623ce80-6bff-11eb-91e9-34decf59e59b.jpg)

1.How to change the settings in yml file in meter.yml and SDM120.yml
2. The value show like exponential in Grafana, But I tested separate in MTester it shows right value (images attached)
![IMG_20210211_002914](https://user-images.githubusercontent.com/48491061/107557962-3d596280-6c00-11eb-8847-6b7490d79f23.jpg)

**Comment by GuillermoElectrico** [comment]
I see the problem (1612968047496739000 is not a float) but I don't know why it gets that result. I have never run into this problem in my tests with my equipment.

**Comment by karan369** [comment]
Hi, 
Further I also checked with other modules
1. zabbix libmodbus : Its easily converted float to actual value ( Result is passed)
`Read holding register
Address: 99
Datatype: Float, 32 bit
Endiannes: Mid-Little Indian (CDAB)
Fitst reg: 0
Output:
240.51
2. Telegraf : Not showing actual value 
```
`byte order: CDAB
Data type: FLOAT32
scale:0.01
Addres: [99, 
100]`
```
Output:
[ 11314829.39
1613071141000000000] ( The same output is given from python Modbus logger script)

- How to improve this.?
- Do you have any idea to change to get actual value?
- Any formula to convert ?

**Comment by GuillermoElectrico** [comment]
Without being able to replicate it locally, I have no idea why this result is giving you so much (also now I don't have time to delve into the subject).

**Comment by karan369** [comment]
Okay fine. Keep in touch.

**Comment by karan369** [comment]
Hi,
I collected some more details for this device.
Data type: 32 bit float, little endian byte swap
and Two register
This combines 2 16 bit Modbus register, It displayed byte order in Little endian byte swap

How to add the script in data_format .

Kindly provide the reference for further improvement.
