### ISSUE TITLE
New Data type float 32  little endian byte swap not get real value

### ISSUE THREAD

**Issue by karan369** [GuillermoElectrico/modbus-logger#8]
Hi,
Need to add  new Data type
Data type: 32 bit float, little endian byte swap
and Two register
This combines 2 16 bit Modbus register, It displayed byte order in Little endian byte swap
We want like this
[
![modbusflot32](https://user-images.githubusercontent.com/48491061/107857628-72aabe00-6e55-11eb-9927-3bb39668f4b4.jpeg)
](url)
How to add the script in data_format .

Tested Result shown below ( is not real value)
type=holding_register voltage1=11313223.24 1613223318000000000

Final Real Value should be between **238.45 to 239.10**

What is the solution for further improvement.

**Comment by GuillermoElectrico** [comment]
Have you tried data type 4 (4 = Long (CDAB)), to see what it gives you?

**Comment by GuillermoElectrico** [comment]
I have added a new data type 7 = Float (CDAB), I have not been able to test it, so it is in experimental mode (it is untested). I guess that's what you need.

**Comment by karan369** [comment]
> I have added a new data type 7 = Float (CDAB), I have not been able to test it, so it is in experimental mode (it is untested). I guess that's what you need.

Hi, Thanks for your reply. I tested, but need to change 'device'  instead of 'meter (like meter['id']' )yml file name, its affected in all
```
elif parameters[parameter][2] == 7:
                                        resultadoTemp = masterRTU.execute(meter['id'], cst.READ_INPUT_REGISTERS, parameters[parameter][0], parameters[parameter][1])
                                        resultadoTemp2 = (resultadoTemp[1]<<16)|resultadoTemp[0]
                                        resultado = [0,0]
                                        resultado[0] = struct.unpack('f', struct.pack('I', resultadoTemp2))[0]
                                datas[list][parameter] = resultado[0]
```
But i try change manually and will update the result.

**Comment by karan369** [comment]
Hello,
I tested, this also not given real value

 Output-1  (7, Float)
```
fieldKey fieldType
-------- ---------
ReadTime float
VTest-9  integer
VTest-9 value : 1131256083 
```
Output-2 ( 4, Long) ---- The same result is given
```
VTest-10 integer
VTest-10 value: 1131378267
```

**Comment by GuillermoElectrico** [comment]
Works for me (239.4623260498047),  the new data type 7 does is obtain a Long (CDAB) and convert it to float with: 

resultado[0] = struct.unpack('f', struct.pack('I', (resultadoTemp[1]<<16)|resultadoTemp[0]))[0]

**Comment by karan369** [comment]
Great.. Now The Same Works for me.

                      `      233.1858367919922  1  Secure-Test-1`

Thanks Lot for your support.

**Comment by karan369** [comment]
Hi,
I tested in USB Converter (ModbusRTU), this shown error... But another one converter Modbus TCP---tested Okay

USB Converter Error below
```
`--- Logging error ---
Traceback (most recent call last):
  File "./read_energy_meter.py", line 126, in collect_and_store
    resultadoTemp = masterRTU.execute(meter['id'], cst.READ_HOLDING_REGISTERS, parameters[parameter][0], parameters[parameter][1])
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/utils.py", line 39, in new
    raise excpt
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/utils.py", line 37, in new
    ret = fcn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/modbus.py", line 306, in execute
    response_pdu = query.parse_response(response)
  File "/usr/local/lib/python3.6/dist-packages/modbus_tk-1.1.0-py3.6.egg/modbus_tk/modbus_rtu.py", line 46, in parse_response
    raise ModbusInvalidResponseError("Response length is invalid {0}".format(len(response)))
modbus_tk.exceptions.ModbusInvalidResponseError: Response length is invalid 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./read_energy_meter.py", line 363, in <module>
    func=lambda: collector.collect_and_store())
  File "./read_energy_meter.py", line 316, in repeat
    func(*args, **kwargs)
  File "./read_energy_meter.py", line 363, in <lambda>
    func=lambda: collector.collect_and_store())
  File "./read_energy_meter.py", line 172, in collect_and_store
    log.error("Unexpected error:", sys.exc_info()[0])
Message: 'Unexpected error:'
Arguments: (<class 'modbus_tk.exceptions.ModbusInvalidResponseError'>,)
Response length is invalid 0
```
`
How to solve this issue. Is Need to change in modbus_tk  package.

**Comment by karan369** [comment]
Hi,
Now USB Converter also worked--tested okay, I tried to change the meter name is solved.
